name = "DiagHamInterface"
uuid = "2f27495d-c82b-46d5-b81b-1bb9aa58c4d5"
version = "0.1.0"
authors = ["Andreas Feuerpfeil <development@manybodylab.com>"]

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
DelimitedFiles = "1"
Format = "1.3.7"
Preferences = "1.5.0"
Printf = "1"
SparseArrays = "1"
julia = "1.10"
