[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
DiagHamInterface = "2f27495d-c82b-46d5-b81b-1bb9aa58c4d5"

[compat]
Documenter = "1"
Literate = "2"
DiagHamInterface = "1.0"
